### ISSUE TITLE
Location Component Simplification

### ISSUE THREAD

**Issue by jordanwillis** [sandeepdhillo/TeaCozy#4]
Another thing that I wanted to recommend is to practice re-using class names for components that serve the same purpose.  You did a great job of this re-using the `.item` class for each tea of the month section.  Each section represents the same conceptual component so it makes sense to apply the same class to all of it.

Similarly, I would recommend using the same approach for each of your location boxes.  Perhaps a good class name could be `.location`.  This further improves the structure and semantics of your HTML and even simplifies your CSS.

Instead of having to combine classes together in a single selector like this:

https://github.com/sandeepdhillo/TeaCozy/blob/9ebbc3080da9fa76aefe38216a034713cbb3e03c/Dropbox/Projects/TeaCozy/resources/style.css#L96-L103

You can just use the single reusable class name.

``` css
.location {
  color:white;
  background:black;
  display:inline-block;
  align-text:center;
  flex-basis: 280px;
  height: 280;
}
```

On a side note, watch our for your indentation in your stylesheet as well.
